### PR TITLE
[WIP] Aira to PY3 #127

### PR DESCRIPTION
**Pull request by kickapoo**
This a pull request from same as PR: https://github.com/openmeteo/aira/pull/127 ( For history check the related commends)

- [x] Editor Issues
- [x] Split Managament Command for En, Gr cases
- [x] Fix broken test cases

### CODE REVIEW

**Comment by aptiko** [comment]
In some unit tests you have "verion" instead of "version".

Also please convert each one of these unit tests to a TestCase of which setUp() will be executing `call_command()` and a `test_output_message()` method will just be executing the `assertIn()`.

**Comment by aptiko** [comment]
Ah, and rebase onto master so that Travis will run.

**Comment by kickapoo** [comment]
@aptiko Please recheck

**Comment by aptiko** [comment]
OK, now `setUp()` does the work and `test_*()` checks how the work was done. This is what I asked (although I have to admit I'm not certain about it :-). Now, `call_command()` does a lot more than showing a phrase in the output. Is it possible to create other `test_*()` methods that check other things?

**Comment by kickapoo** [comment]
Travis CI is failing and from the error log

1. No raster folder is provided see also issue-question https://github.com/openmeteo/aira/issues/124
2. An new test in failing even in my local tests are passing - aira.tests.test_management.PopulateCoeffsTestGRVersion

Please advice

**Comment by kickapoo** [comment]
Also, I will like include in this PR a minor folder rename
`aira_project/airadb_coeffs` --> `aira_project/initial_data`

**Comment by aptiko** [comment]
I can't follow any more, so let's accept the pull request. Please rebase it, reordering and squashing related commits as needed.

(The last failing test in Travis is very likely because of different locale settings; let's ignore that for now.)

**Comment by kickapoo** [comment]
@aptiko Maybe now ?

**Comment by aptiko** [comment]
Made some changes in the commit messages and pushed.

**Pull request closed without merging**
