### PR TITLE
Update Profile model with receivers against User model

### PR DESCRIPTION
**Pull request by kickapoo**
- Minor PEP8
- Update Profile Admin settings
- Add singals to User model create, save actions
- Fix typo in Variable name
- Add Unit Test
- Update management command demo_user

### CODE REVIEW

**Comment by aptiko** [comment]
It would be good to unit test the receivers.

As for `get_supervised()`, maybe it's not needed at all. The code that runs it might do the query itself. Of course I can't tell with certainty since `get_supervised()` is not yet being used anywhere. We might delay defining this function until we actually use it.

**Comment by kickapoo** [comment]
`get_supervised()` in known to me that will be used in various places, like Accounts/Profile, Homepage and if user can edit (a User can edit his/her fields or his/her supervised users fields). It will be very handy to have this ready in the Profile object because is an extend of User object (current_user.profile.get_supervised())

- [ ] Make receivers Unit Test for Profile Model

**Comment by kickapoo** [comment]
@aptiko Please revisit

**Comment by aptiko** [comment]
In `aira.models.py` the `from django ...` import should be in alphabetical order.

Also add a trailing comma to line 51 (`('el', 'Ελληνικά')`).

In `test_management.py` put the `from django ...` imports in alphabetical order and leave a blank line between them and the `from aira ...` import.

You don't need `tearDown()` here; Django empties the database at the end of each test.

In `test_models.py`, again you don't need `tearDown()`. 

Modify the `TestCase` so that there is only one `assertX()` statement in each test.

**Comment by kickapoo** [comment]
@aptiko please review

**Comment by aptiko** [comment]
I merged this after making these changes:

- I reverted the changes to `test_management.py`
- I renamed the test to `UserTestCase` (from `TestUserModel`) and removed all comments.

**Pull request closed without merging**
