### PR TITLE
Update UnitTest to use mommy lib (fixes #136)

### LINKED ISSUE #136: Update Aira TestCase to use Mommy
https://github.com/vandersonmota/model_mommy

### PR DESCRIPTION
**Pull request by kickapoo**

### CODE REVIEW

**Comment by aptiko** [comment]
Instead of this:
```
registered_user_data = {
    'username': 'batman',
    'email': 'batman@cave.com',
    'password': 'thegoatandthesheep',
    'is_active': True
}
self.registered_user = mommy.make(User, **registered_user_data)
```
you could write this:
```
self.registered_user = mommy.make(
    User,
    username='batman',
    email='batman@cave.com',
    password='thegoatandthesheep',
    is_active=True,
}
```
It seems to be more standard in the mommy documentation, and I also think it's clearer to read (especially if you need to create many things).

In addition, I'd prefer it if you don't set `password` this way, but either not set it at all or use `.set_password()`; this is for consistency with the other tests, and because `thegoatandthesheep` looks like a password and not like a hash.

Finally, you have this comment:
```
# hash password
```
What does this mean? Either write it clearly, or remove the comment.

**Comment by kickapoo** [comment]
@aptiko 

Ty for your comments. 

1. Yes, I saw is also in documentation but I didn't like it. Anyway 
    - [ ] Update Mommy object creation
2. `.set_password()` its necessary as mommy doesn't "hash" the field. As a result the test that uses `self.client.login(username, password` always failed because of unhashed password.
  For a more clear example check this stackoverflow: https://stackoverflow.com/questions/33635322/testing-login-with-model-mommy

**Comment by kickapoo** [comment]
@aptiko Please revisit

**Comment by aptiko** [comment]
Please fix the commit message
```
Update UnitTest to use mommy lib (fixes #136)
```
Use this instead:
```
Update unit tests to use model-mommy (fixes #136)
```
Then merge.

**Pull request merged**
